---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.4
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[docker-registry::application_server]
    attributes:
      docker-registry:
        owner: dockreg
        group: dockreg
        secret_key: fksldjriohl2kfsn2lh342kjfdeaslhkhfskjnhalknfk4232snfkldjfsdf3242
